spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 189274abcd
    url: jdbc:mysql://127.0.0.1:3306/meethere?useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
