spring:
  profiles:
    active: dev

mybatis:
  mapper-locations:
    classpath:com/ecnu/meethere/user/dao/xml/*.xml,
    classpath:com/ecnu/meethere/news/dao/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  servlet:
    session:
      cookie:
        name: SESSIONID
        http-only: true

redis:
  expires:
    news:
      expires: 120
      timeUnit: MINUTES
      randomRange: 20
